[package]
name = "spl-type-length-value"
version = "0.2.0"
description = "Solana Program Library Type-Length-Value Management"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
derive = ["dep:spl-type-length-value-derive"]

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
domichain-program = { path = "../../../domichain/sdk/program" }
spl-discriminator = { version = "0.1.0", path = "../discriminator" }
spl-program-error = { version = "0.2.0", path = "../program-error" }
spl-type-length-value-derive = { version = "0.1.0", path = "./derive", optional = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
